<<<<<<< HEAD
"""
Django settings for mesaging_app project.

Generated by 'django-admin startproject' using Django 5.2.6.'

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

=======
import os
>>>>>>> 6e94a15ad0e04ccb334ae164477d76e6f22c87ac
from pathlib import Path
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent

<<<<<<< HEAD
SECRET_KEY = 'django-insecure-i$s$qqt1%(5ev%i$4(at_kqwmtak8t%t=2+pp6k_gpn+#k&t=2'
DEBUG = True
ALLOWED_HOSTS = []
=======
SECRET_KEY = 'django-insecure-secret-key'
DEBUG = False
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
>>>>>>> 6e94a15ad0e04ccb334ae164477d76e6f22c87ac

INSTALLED_APPS = [
    # Django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD

    # Third-party apps
    'rest_framework',
    'django_filters',

    # Local apps
    'chats.apps.ChatsConfig',   #  only this — do NOT also include 'chats'
    
]

# If you have a custom User model inside chats/models.py
=======
    'rest_framework',
    'django_filters',
    'chats.apps.ChatsConfig',
]

>>>>>>> 6e94a15ad0e04ccb334ae164477d76e6f22c87ac
AUTH_USER_MODEL = 'chats.User'

# -------------------------------------------------------------------
#  MIDDLEWARE
# -------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

<<<<<<< HEAD
# -------------------------------------------------------------------
#  URLS & WSGI
# -------------------------------------------------------------------
=======
>>>>>>> 6e94a15ad0e04ccb334ae164477d76e6f22c87ac
ROOT_URLCONF = 'messaging_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
<<<<<<< HEAD
=======
        'OPTIONS': {'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
        ]},
    },
]

WSGI_APPLICATION = 'messaging_app.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('MYSQL_DATABASE'),
        'USER': os.environ.get('MYSQL_USER'),
        'PASSWORD': os.environ.get('MYSQL_PASSWORD'),
        'HOST': os.environ.get('MYSQL_HOST', 'db'),
        'PORT': os.environ.get('MYSQL_PORT', '3306'),
>>>>>>> 6e94a15ad0e04ccb334ae164477d76e6f22c87ac
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",

<<<<<<< HEAD
WSGI_APPLICATION = 'messaging_app.wsgi.application'

# -------------------------------------------------------------------
#  DATABASE
# -------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -------------------------------------------------------------------
#  PASSWORD VALIDATION
# -------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# -------------------------------------------------------------------
# INTERNATIONALIZATION
# -------------------------------------------------------------------
=======
         },
    }
}

AUTH_PASSWORD_VALIDATORS = []
>>>>>>> 6e94a15ad0e04ccb334ae164477d76e6f22c87ac
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
<<<<<<< HEAD

# -------------------------------------------------------------------
# STATIC FILES
# -------------------------------------------------------------------
STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------------------------------------------------------------
# DJANGO REST FRAMEWORK SETTINGS
# -------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 'chats.auth.CustomJWTAuthentication',  # uncomment ONLY if file exists
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# -------------------------------------------------------------------
# JWT SETTINGS (djangorestframework-simplejwt)
# -------------------------------------------------------------------
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# -------------------------------------------------------------------
# CACHING (optional)
# -------------------------------------------------------------------
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
=======
STATIC_URL = '/static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
>>>>>>> 6e94a15ad0e04ccb334ae164477d76e6f22c87ac
