version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/messaging_app
    ports:
      - 8000:8000
    image: app:messaging_app
    container_name: messaging_app
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"     # maps host 3307 → container 3306
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: messaging_web
    command: >
      sh -c "python manage.py migrate &&
             command: python manage.py runserver 0.0.0.0:8000"

  volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
